### ISSUE TITLE
the download url of vgg16.pkl is missing! how can i get it, please help me,thanks a lot

### ISSUE THREAD

**Issue by shuaidaming** [fvisin/reseg#8]

**Comment by fvisin** [comment]
Hello, unfortunately this code is not maintained anymore and Theano itself has been discountinued at the end of 2017. I am not sure where you could find the pretrained weights for VGG for Theano now, but it would probably be best to reproduce ReSeg in an actively developed framework such as JAX, Tensorflow or PyTorch rather than trying to get this code to work as is.
